spring.application.name=AwardedMovies

spring.datasource.url=jdbc:mysql://localhost:3306/awarded_movies
spring.datasource.username=root
spring.datasource.password=admin@123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html